services:
  db:
    container_name: db
    image: mysql:5.7

    expose:
      - 3306
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: exampleDb
      MYSQL_USER: flaskapp
      MYSQL_PASSWORD: flaskapp
      MYSQL_ROOT_PASSWORD: flaskapp
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      
  app:
    container_name: app
    image: arnontzori/kubernetes-learning-app:1.1.2
    ports:
      - 80:80
    depends_on:
      db:
        condition: service_healthy
    restart: always
    environment:
      DB_HOST: db
      DB_USER: flaskapp
      DB_PASS: flaskapp
      DB_NAME: exampleDb
      BACKEND: "http://localhost"